#PBS -N seg_eval
#PBS -o /ghome/gaocs/FCM-UFC/err_out/seg_eval.out
#PBS -e /ghome/gaocs/FCM-UFC/err_out/seg_eval.err
#PBS -l nodes=1:gpus=1:A,walltime=350:00:00
#PBS -r y
cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes and gpus:
cat $PBS_NODEFILE
cat $PBS_GPUFILE


startdocker -u " -v /gdata/gaocs:/gdata/gaocs  -v /gdata1/gaocs:/gdata1/gaocs -v /gdata2/gaocs:/gdata2/gaocs " \
            -P /ghome/gaocs \
            -s "/ghome/gaocs/FCM-UFC/job/dinov2_seg.sh hyperprior hybrid kmeans 10 8 0.0001 1000 180 256-256 0.0005 0.001 0.01" \
            bit:5000/liuzj_dinov2:v1

