#PBS -N dpt_hm_hybrid
#PBS -o /ghome/gaocs/FCM-UFC/err_out/dpt_hm_hybrid.out
#PBS -e /ghome/gaocs/FCM-UFC/err_out/dpt_hm_hybrid.err
#PBS -l nodes=1:gpus=2:B,walltime=350:00:00
#PBS -r y
cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes and gpus:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

# -s "/ghome/gaocs/FCM-UFC/job/dinov2_dpt.sh hyperprior hybrid kmeans 10 8 0.0001 1000 180 256-256 0.0005" \

startdocker -u " -v /gdata/gaocs:/gdata/gaocs  -v /gdata1/gaocs:/gdata1/gaocs -v /gdata2/gaocs:/gdata2/gaocs " \
            -P /ghome/gaocs \
            -s "/ghome/gaocs/FCM-UFC/job/dinov2_dpt.sh hm hybrid uniform 0 10 0.0001 1000 180 256-256 0.0005" \
            bit:5000/liuzj_dinov2:v1

